cta:
  bucket: null
  version: null
  domain: null
name: Charlie Tan
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
typography_spectrum: 0.1627319
color:
  saturation: 0.5601504
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#F5F4F0'
    - '#010101'
    - '#30302F'
    - '#5C5C5A'
    - '#B6B5B2'
  rhythmicContrast: 0.06661046
layout_spectrum: 0.2284992
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
