purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2808808
  brandStrength: 0.3034371
  lightness: 0.6632653
  brandColors:
    - '#ffffff'
  rhythmicContrast: 0.3088077
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Charlie Tan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3990332
layout_spectrum: 0.4548872
