name: Charlie Tan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1627319
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70603C'
    - '#C7C4BF'
    - '#39311A'
    - '#948878'
    - '#0E0D09'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
