favicon: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.1627319
color:
  saturation: 0.8093448
  brandStrength: 0.8888292
  lightness: 0.6288937
  brandColors:
    - '#70603C'
    - '#C7C4BF'
    - '#39311A'
    - '#948878'
    - '#0E0D09'
  rhythmicContrast: 0.7062299
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4473684
analytics:
  twitter: null
  google: null
  facebook: null
name: Charlie Tan
